### ISSUE TITLE
In my Android API level 21 (Lollipop) getting error.

### ISSUE THREAD

**Issue by raghavpai** [Kotlin/kotlinx-datetime#114]
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at kotlinx.datetime.Instant.<clinit>(Instant.kt:93)
        at kotlinx.datetime.Clock$System.now(Clock.kt:17)
        
        
             Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/eu.baroncelli.dkmpsample-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at kotlinx.datetime.Instant.<clinit>(Instant.kt:93) 
        at kotlinx.datetime.Clock$System.now(Clock.kt:17) 
        at

**Comment by SchweinchenFuntik** [comment]
https://github.com/Kotlin/kotlinx-datetime#using-in-your-projects
> If you target Android devices running below API 26, you need to use Android Gradle plugin 4.0 or newer and enable core library desugaring.

https://developer.android.com/studio/write/java8-support#library-desugaring

have you done these steps?

**Comment by raghavpai** [comment]
Thank you it is working with desugaring.
