### ISSUE TITLE
[Multiplatform] Issues publishing when included into multi-target project

### ISSUE THREAD

**Issue by Micha-ohne-el** [Kotlin/kotlinx-datetime#220]
Hi there!

I'm having issues publishing my library (to mavenLocal) when I add `kotlinx-datetime` to my dependencies. I was hoping you could have a look.
I have prepared a minimal sample project, with which I can replicate the problem: [Please see here.](https://github.com/Micha-ohne-el/kotlinx-datetime-test) It's an IntelliJ IDEA project, I hope that is alright.

When I execute the build task `publishToMavenLocal`, I consistently get an error. The error only occurs when more than one build target (such as `jvm`, `linuxX64` or `js`) is specified in my `build.gradle.kts`.
The error occurs at the build step `compileCommonMainKotlinMetadata` and it reads the following:
```
java.lang.IllegalStateException: e: Could not find "/home/micha/Projects/kotlinx-datetime-test/build/kotlinSourceSetMetadata/commonMain/org.jetbrains.kotlinx-kotlinx-datetime/org.jetbrains.kotlinx-kotlinx-datetime-commonMain.klib" in [/home/micha/.local/share/kotlin/daemon]
	at org.jetbrains.kotlin.library.SingleFileResolveKt$resolveSingleFileKlib$1.fatal(SingleFileResolve.kt:21)
	at org.jetbrains.kotlin.library.KotlinLibrarySearchPathResolver.resolve(SearchPathResolver.kt:175)
	at org.jetbrains.kotlin.library.KotlinLibrarySearchPathResolver.resolve(SearchPathResolver.kt:181)
	at org.jetbrains.kotlin.library.CompilerSingleFileKlibResolveStrategy.resolve(SearchPathResolver.kt:302)
	at org.jetbrains.kotlin.library.SingleFileResolveKt.resolveSingleFileKlib(SingleFileResolve.kt:24)
	at org.jetbrains.kotlin.library.SingleFileResolveKt.resolveSingleFileKlib$default(SingleFileResolve.kt:15)
	at org.jetbrains.kotlin.cli.metadata.KlibMetadataDependencyContainer.<init>(K2MetadataKlibSerializer.kt:122)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataKlibSerializer$serialize$analyzer$1.invoke(K2MetadataKlibSerializer.kt:54)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataKlibSerializer$serialize$analyzer$1.invoke(K2MetadataKlibSerializer.kt:48)
	at org.jetbrains.kotlin.cli.metadata.CommonAnalysisKt.runCommonAnalysisForSerialization(CommonAnalysis.kt:42)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataKlibSerializer.serialize(K2MetadataKlibSerializer.kt:53)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:117)
	at org.jetbrains.kotlin.cli.metadata.K2MetadataCompiler.doExecute(K2MetadataCompiler.kt:40)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1623)
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
As you will (hopefully) see in my sample project, removing all but one build target fixes the issue. It does not matter which is removed and which is kept.
Additionally, going back to version `0.3.3` also fixes the issue.

To clarify: I am able to build and run all of my code, just not publish it.

I'm not sure what the cause of this error could be and would really appreciate some guidance here.
I'm not particularly knowledgeable when it comes to any of this, so forgive me if I have mixed up some terms.

Thanks for your time!

**Comment by dkhalanskyjb** [comment]
Hi! I was on a vacation, so couldn't answer quickly, sorry for the delay. Typically, it's a good idea to go to the Kotlin Slack channel with such issues. It is somewhat active and there is a number of helpful people.

In this case, the issue is simple: datetime 0.4.0 is only compatible with the compiler 1.7.0+. Changing the compiler version in your project fixed the issue:
```patch
diff --git a/build.gradle.kts b/build.gradle.kts
index 495b5b5..c0dab1f 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -1,5 +1,5 @@
 plugins {
-    kotlin("multiplatform") version "1.6.21"
+    kotlin("multiplatform") version "1.7.0"
 
     id("maven-publish")
 }
```

**Comment by Micha-ohne-el** [comment]
Oh damn, thanks for the easy fix and the explanation!

Take care
