### ISSUE TITLE
Can't use Instant field of data class when saving to Firebase realtime database.

### ISSUE THREAD

**Issue by jeddchoi** [Kotlin/kotlinx-datetime#274]
I am developing an android application using firebase realtime database.

According to [firebase document](https://firebase.google.com/docs/database/android/read-and-write?hl=ko#basic_write), 
> Pass a custom Java object, if the class that defines it has a default constructor that takes no arguments and has public getters for the properties to be assigned.

So I made custom kotlin data class with Instant field as below : 
```kotlin
import kotlinx.datetime.Clock
import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

@Serializable
data class UserStatus(
// ...
   val updatedAt: Instant = Clock.System.now(),
// ...
}
```
It has default constructor and only public getters.

```kotlin
val newUserStatus = UserStatus()
Firebase.database.reference.child(REFERENCE_USER_STATUS_NAME).child(createdUser.uid).setValue(newUserStatus).await()
```

But, because of Instant field of the class, the error occurs as below : 

```
com.google.firebase.database.DatabaseException: Invalid key: value$kotlinx_datetime. Keys must not contain '/', '.', '#', '$', '[', or ']'
at com.google.firebase.database.core.utilities.Validation.validateWritableKey(Validation.java:123)
at com.google.firebase.database.core.utilities.Validation.validateWritableObject(Validation.java:106)
at com.google.firebase.database.core.utilities.Validation.validateWritableObject(Validation.java:107)
at com.google.firebase.database.DatabaseReference.setValueInternal(DatabaseReference.java:283)
at com.google.firebase.database.DatabaseReference.setValue(DatabaseReference.java:159)
//...
```

When I comment that Instant field and build, It works well.
What am I missing?

**Comment by dkhalanskyjb** [comment]
I think this question should be directed to the Firebase community, not here. Maybe StackOverflow would help. Judging by the error message, Firebase is trying to access the internal implementation details of `Instant`. This is clearly incorrect behavior: whose business is it how exactly do we implement our classes? I guess Firebase allows you to fix that somehow, but I have no idea how.
