### ISSUE TITLE
Seconds not optional in ISO 8601 parser

### ISSUE THREAD

**Issue by guelo** [Kotlin/kotlinx-datetime#466]
ISO 8601 allows seconds to be ommitted but the default parser requires them.

```
import kotlinx.datetime.Instant
import kotlinx.datetime.format.DateTimeComponents
import kotlinx.datetime.format.byUnicodePattern
import org.junit.Test

class Test {
    val ISO8601NoSeconds = "2024-12-12T02:30Z"
    val ISO8601WithSeconds = "2024-12-12T02:30:00Z"

    @Test
    fun test1() {
        val instant = Instant.parse(ISO8601NoSeconds) 
        println("Parsed: $instant")
    }

    /**
Output:
Failed to parse an instant from '2024-12-12T02:30Z'
kotlinx.datetime.DateTimeFormatException: Failed to parse an instant from '2024-12-12T02:30Z'
at app//kotlinx.datetime.Instant$Companion.parse(Instant.kt:79)
at app//kotlinx.datetime.Instant$Companion.parse$default(Instant.kt:69)
at app//com.fanfly.model.Test.test1(ShowTest.kt:14)
at java.base@17.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base@17.0.10/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base@17.0.10/java.lang.reflect.Method.invoke(Unknown Source)
at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:54)
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
at java.base@17.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.10/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base@17.0.10/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base@17.0.10/java.lang.reflect.Method.invoke(Unknown Source)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
at jdk.proxy1/jdk.proxy1.$Proxy4.processTestClass(Unknown Source)
at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:181)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:130)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:101)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:61)
at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:122)
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:69)
at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: kotlinx.datetime.DateTimeFormatException: Failed to parse value from '2024-12-12T02:30Z'
at app//kotlinx.datetime.format.AbstractDateTimeFormat.parse(DateTimeFormat.kt:136)
at app//kotlinx.datetime.Instant$Companion.parse(Instant.kt:77)
... 45 more
Caused by: kotlinx.datetime.internal.format.parser.ParseException: Errors: position 16: 'Expected : but got Z', position 10: 'Expected t but got T', position 0: 'Expected - but got 2', position 0: 'Expected + but got 2'
at app//kotlinx.datetime.internal.format.parser.Parser.match-impl(Parser.kt:197)
at app//kotlinx.datetime.internal.format.parser.Parser.match-impl$default(Parser.kt:186)
at app//kotlinx.datetime.format.AbstractDateTimeFormat.parse(DateTimeFormat.kt:134)
... 46 more
     */

    @Test
    fun test2() {
        val instant = Instant.parse(ISO8601WithSeconds)
        println("Parsed: $instant")
    }

    /**
Output:
Parsed: 2024-12-12T02:30:00Z
     */

    @Test
    fun test3() {
        val correctFormatter = DateTimeComponents.Format {
            byUnicodePattern("uuuu-MM-dd'T'HH:mm[:ss][.SSS]'Z'")
        }
        println("Parsed: ${Instant.parse(ISO8601WithSeconds, correctFormatter)}")
        println("Parsed: ${Instant.parse(ISO8601NoSeconds, correctFormatter)}")
    }

    /**
Output:
Parsed: 2024-12-12T02:30:00Z
Parsed: 2024-12-12T02:30:00Z
     */
}


```

**Comment by dkhalanskyjb** [comment]
Hi! ISO 8601 specifies dozens of formats, and for each data structure, we've deliberated on the most suitable one. The documentation for https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime.format/-date-time-components/-formats/-i-s-o_-d-a-t-e_-t-i-m-e_-o-f-f-s-e-t.html does refer to a specific format: ISO-8601-1:2019, 5.4.2.1b) This format does not allow omitting seconds.

If you want a different format, you can specify it yourself. For example:
```kotlin
import kotlinx.datetime.*
import kotlinx.datetime.format.*

fun main() {
    val format = DateTimeComponents.Format {
        dateTime(LocalDateTime.Formats.ISO)
        offset(UtcOffset.Formats.ISO)
    }
    val ISO8601NoSeconds = "2024-12-12T02:30Z"
    val ISO8601WithSeconds = "2024-12-12T02:30:00Z"
    println(Instant.parse(ISO8601NoSeconds, format))
    println(Instant.parse(ISO8601WithSeconds, format))
}
```
