### ISSUE TITLE
NoClassDefFoundError Ljava/time/ZoneOffset

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx-datetime#48]
On specific phone - zebra tc25 get a runtime exception. Stacktrace ->

```
java.lang.ClassNotFoundException: Didn't find class "java.time.ZoneOffset" on path: DexPathList[[zip file "/data/app/com.p1ng2win.gabiapplication-2/base.apk"],nativeLibraryDirectories=[/data/app/com.p1ng2win.gabiapplication-2/lib/arm64, /data/app/com.p1ng2win.gabiapplication-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at kotlinx.datetime.TimeZone.<clinit>(TimeZoneJvm.kt:32)
    at com.p1ng2win.gabiapplication.framework.stuff.exts.KotlinExtensionsKt.systemLocalDate(KotlinExtensions.kt:38)
    at com.p1ng2win.gabiapplication.framework.model.WorkerVM$onChangeFIO$1.invokeSuspend(WorkerVM.kt:38)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:330)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
    at kotlinx.coroutines.BuildersKt.launch
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
    at kotlinx.coroutines.BuildersKt.launch$default
    at com.p1ng2win.gabiapplication.framework.model.WorkerVM.onChangeFIO(WorkerVM.kt:30)
    at com.p1ng2win.gabiapplication.ui.fragments.actions.init.employee.EmployeeFragment$initView$1.invoke(EmployeeFragment.kt:54)
    at com.p1ng2win.gabiapplication.ui.fragments.actions.init.employee.EmployeeFragment$initView$1.invoke(EmployeeFragment.kt:25)
    at com.p1ng2win.gabiapplication.ui.adapters.EmployeeAdapter$employeeDelegate$1$1.onClick(EmployeeAdapter.kt:23)
    at android.view.View.performClick(View.java:5637)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
    at android.view.View$PerformClick.run(View.java:22433)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6123)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneOffset;
    at kotlinx.datetime.TimeZone.<clinit>(TimeZoneJvm.kt:32)
    at com.p1ng2win.gabiapplication.framework.stuff.exts.KotlinExtensionsKt.systemLocalDate(KotlinExtensions.kt:38)
    at com.p1ng2win.gabiapplication.framework.model.WorkerVM$onChangeFIO$1.invokeSuspend(WorkerVM.kt:38)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:330)
    at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
    at kotlinx.coroutines.BuildersKt.launch
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
    at kotlinx.coroutines.BuildersKt.launch$default
    at com.p1ng2win.gabiapplication.framework.model.WorkerVM.onChangeFIO(WorkerVM.kt:30)
    at com.p1ng2win.gabiapplication.ui.fragments.actions.init.employee.EmployeeFragment$initView$1.invoke(EmployeeFragment.kt:54)
    at com.p1ng2win.gabiapplication.ui.fragments.actions.init.employee.EmployeeFragment$initView$1.invoke(EmployeeFragment.kt:25)
    at com.p1ng2win.gabiapplication.ui.adapters.EmployeeAdapter$employeeDelegate$1$1.onClick(EmployeeAdapter.kt:23)
    at android.view.View.performClick(View.java:5637)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
    at android.view.View$PerformClick.run(View.java:22433)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6123)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

systemLocalDate ext - > 

```
fun systemLocalDate(): LocalDate =
    Clock.System.todayAt(TimeZone.currentSystemDefault())
```

**Comment by JakeWharton** [comment]
Is the phone running Android API 26 or newer? If not, you need to use AGP 4.0 or newer and enable core library desugaring: https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by P1NG2WIN** [comment]
> Is the phone running Android API 26 or newer? If not, you need to use AGP 4.0 or newer and enable core library desugaring: https://developer.android.com/studio/write/java8-support#library-desugaring

Thanks! I will add `coreLibraryDesugaringEnabled`
