### ISSUE TITLE
Crash on Android below API 26 for ClassNotFoundException on java.time.Instant (without desugaring)

### ISSUE THREAD

**Issue by FrostRocket** [Kotlin/kotlinx-datetime#64]
When using this library on Android, devices running below API 26 will crash with a class not found exception on java.time.Instant. 

I was under the impression we'd transitively get the java time dependencies by simply importing this library, but it won't work unless you enable coreLibraryDesugaring. I'd consider this a bug. 

Here's a trace, though I'm sure you don't need it:

```10-27 00:58:38.179 17460-17460/com.package.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.package.myapp, PID: 17460
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at kotlinx.datetime.Instant.<clinit>(Instant.kt:75)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/com.package.myapp/base.apk"],nativeLibraryDirectories=[/data/app/com.package.myapp-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at kotlinx.datetime.Instant.<clinit>(Instant.kt:75) 
        at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:122) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    	Suppressed: java.lang.ClassNotFoundException: java.time.Instant
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 35 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available```

**Comment by JakeWharton** [comment]
This is working as intended, but better documentation is needed to message this requirement.

**Comment by P1NG2WIN** [comment]
https://github.com/Kotlin/kotlinx-datetime/issues/48#issuecomment-687264154

**Comment by FrostRocket** [comment]
With desugaring enabled, you're given the entirety of the java.time library at your disposal. I have to ask then: other than the API footprint being slightly modified (with less functionality available, I might add), why would you bother with this "wrapper"?

**Comment by JakeWharton** [comment]
Multiplatform, of course.

**Comment by FrostRocket** [comment]
Lol. Fair enough. 

This video helped explain a bit more on the topic: https://www.youtube.com/watch?v=YwN0kAMNvXI&ab_channel=JetBrainsTV

I'm going to close this issue since it's by design.
