### ISSUE TITLE
NoClassDefFoundError: kotlinx/datetime/Clock$System

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx-datetime#70]
Got this error on my kotlin api with Ktor

```

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:152)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:384)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:330)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:275)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:310)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:274)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:290)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:272)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:125)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:245)
        at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:126)
        at io.ktor.server.netty.EngineMain.main(EngineMain.kt:26)
Caused by: java.lang.NoClassDefFoundError: kotlinx/datetime/Clock$System
        at com.p1ng2win.stuff.ExtensionsKt.DateTimeUTC(Extensions.kt:34)
        at com.p1ng2win.model.stuff.MyLogger.writeIntoLogs(MyLogger.kt:64)
        at com.p1ng2win.model.stuff.MyLogger.logAny(MyLogger.kt:46)
        at com.p1ng2win.model.stuff.MyLogger.logAny$default(MyLogger.kt:42)
        at com.p1ng2win.ApplicationKt.mainModule(Application.kt:97)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: kotlinx.datetime.Clock$System
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 29 more
```

_set_ sourceCompatibility  and targetCompatibility 
```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

Could this be due to apiVersion?
```

configure([compileKotlin, compileTestKotlin]) {
    kotlinOptions {
        jvmTarget = "1.8"
        apiVersion = "1.3"
    }
}
```

**Comment by ilya-g** [comment]
No, `apiVersion` setting only affects the standard library declarations.
Can it be that you don't have `kotlinx-datetime` library artifact in the runtime classpath?

**Comment by P1NG2WIN** [comment]
@ilya-g My gradle 

```
buildscript {
    ext.kotlin_version = '1.4.10'
    ext.ktor_version = '1.4.1'
    ext.ktorm_version = "3.2.0"

    repositories {
        jcenter()
    }
    
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.github.jengelman.gradle.plugins:shadow:6.0.0'
    }
}

apply plugin: 'kotlin'
apply plugin: 'application'

group 'com.p1ng2win'
version '1'
mainClassName = "io.ktor.server.netty.EngineMain"

//stuff

sourceCompatibility = 1.8
targetCompatibility = 1.8

configure([compileKotlin, compileTestKotlin]) {
    kotlinOptions {
        jvmTarget = "1.8"
        apiVersion = "1.3"
    }
}

sourceSets {
    main.kotlin.srcDirs = main.java.srcDirs = ['src']
    test.kotlin.srcDirs = test.java.srcDirs = ['test']
    main.resources.srcDirs = ['resources']
    test.resources.srcDirs = ['testresources']
}

repositories {
    mavenLocal()
    jcenter()
    maven { url 'https://maven.husk.pro/repository/internal/' }
    maven { url 'https://kotlin.bintray.com/ktor' }
    maven { url 'https://kotlin.bintray.com/kotlinx' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.1.0")

   //stuff

}
```

**Comment by P1NG2WIN** [comment]
Also, i have dependency in manifest 
![image](https://user-images.githubusercontent.com/27578886/98923189-04fc9800-24dc-11eb-800e-8ac791b88b12.png)

**Comment by P1NG2WIN** [comment]
@ilya-g  Yep, you was right, dependency was not in manifest
