### ISSUE TITLE
java.lang.NoClassDefFoundError (Mix of API levels)

### ISSUE THREAD

**Issue by mustafaozhan** [Kotlin/kotlinx-datetime#92]
Hello I saw closed issues with desugaring for Android but my issue seems not fixed with it.

I moved my Android project to Kotlin Multi Platform and current modules for the android project are below:

android -> client(KMP) -> common(KMP)

android doesn't implement `kotlinx-datetime` directly but client and common has it and uses. When I applied desugaring to only android it didn't work and I applied to all these 3 modules (with Java8 support). [this](https://github.com/CurrencyConverterCalculator/CCC/tree/fix/class-def-no-found) is a branch that you can check.

I just created a build from mentioned branch and published for internal testing (by this way Google runs it in couple of devices)
I have crashes from below android versions
- 5.0.1
- 6.0.1
- 8.0.0 (SDK 26)
- 8.1.0
- 9

Here is the original crash report from Firebase
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lj$/time/Instant;
       at kotlinx.datetime.Instant.<clinit>(Instant.kt:78)
       at kotlinx.datetime.Clock$System.now(Clock.kt:17)
       at com.github.mustafaozhan.ccc.common.data.settings.SettingsRepository.getLastReviewRequest(SettingsRepository.kt:36)
       at com.github.mustafaozhan.ccc.client.viewmodel.main.MainViewModel.shouldShowReview(MainViewModel.kt:19)
       at com.github.mustafaozhan.ccc.android.ui.MainActivity.checkReview(MainActivity.kt:92)
       at com.github.mustafaozhan.ccc.android.ui.MainActivity.onCreate(MainActivity.kt:48)
       at android.app.Activity.performCreate(Activity.java:6013)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
       at android.app.ActivityThread.access$1200(ActivityThread.java:152)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
       at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
       at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:6)
       at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:15)
       at androidx.test.espresso.action.Tap.b(Tap.java)
       at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
       at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
       
       Caused by java.lang.ClassNotFoundException: Didn't find class "j$.time.Instant" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/androidx.test.tools.crawler-1/base.apk", zip file "/data/app/mustafaozhan.github.com.mycurrencies-1/base.apk", zip file "/data/app/mustafaozhan.github.com.mycurrencies-1/split_config.xhdpi.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at kotlinx.datetime.Instant.<clinit>(Instant.kt:78)
       at kotlinx.datetime.Clock$System.now(Clock.kt:17)
       at com.github.mustafaozhan.ccc.common.data.settings.SettingsRepository.getLastReviewRequest(SettingsRepository.kt:36)
       at com.github.mustafaozhan.ccc.client.viewmodel.main.MainViewModel.shouldShowReview(MainViewModel.kt:19)
       at com.github.mustafaozhan.ccc.android.ui.MainActivity.checkReview(MainActivity.kt:92)
       at com.github.mustafaozhan.ccc.android.ui.MainActivity.onCreate(MainActivity.kt:48)
       at android.app.Activity.performCreate(Activity.java:6013)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
       at android.app.ActivityThread.access$1200(ActivityThread.java:152)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
       at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
       at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
       at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:6)
       at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:15)
       at androidx.test.espresso.action.Tap.b(Tap.java)
       at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
       at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
       at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
       at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Thanks in advance!

**Comment by developer--** [comment]
Same for me

**Comment by dkhalanskyjb** [comment]
Thank you for the report! I did manage to reproduce the crash when running the release apk in the Android Emulator for 8.0 (the debug apk seems to work fine). Looking into this.

**Comment by dkhalanskyjb** [comment]
Could you try explicitly adding a dependency on `kotlinx-datetime` in `android/build.gradle.kts`? It seems to have fixed the issue in my small reproducing project.

**Comment by mustafaozhan** [comment]
@dkhalanskyjb Thank you for checking it 👍 I confirm that i didn't received any error so far, closing the issue
